### ISSUE TITLE
Prodigy Hack Permissions

### ISSUE THREAD

**Issue by VillainsRule4000** [Dentamon/Prodigy-Hacks#1]
Is there anything that might happen to my account if I use a Prodigy hack? (Will it get banned, similar to Blooket?)

**Comment by Dentamon** [comment]
i've only tested the add pets and skip tutorial.  If you are willing to help, can you be  my tester?  Use alt accounts if you accept :)

**Comment by VillainsRule4000** [comment]
Yeah, I can be a tester...I have a lot of alts for no reason...

**Comment by VillainsRule4000** [comment]
They all work... (me at level 5 with membership but with level 100 pets, everyones like ???)

**Comment by VillainsRule4000** [comment]
@Dentamon You can tell me here if anything needs testing.
